---
version: "3"
services:
 devopsdb:
   container_name: devopsdb
   image: nagarajukuruva/dbimage
   ports:
     - "3306:3306"

 application:
   container_name: appcontainer
   image: nagarajukuruva/appimage
   ports:
     - "1111:8080"
   depends_on:
     - "devopsdb"
